const  stateLayer = [
    { "sourceLayer": "california-da2p1a", "sourceURL": "mapbox://meghabyte.aw9jcmar" },
    { "sourceLayer": "kansas-4dtskn", "sourceURL": "mapbox://meghabyte.8xd31u2g" },
    { "sourceLayer": "hawaii-dict1k", "sourceURL": "mapbox://meghabyte.8azsjxqd" },
    { "sourceLayer": "kentucky-dtcipr", "sourceURL": "mapbox://meghabyte.a3l2lavz" },
    { "sourceLayer": "iowa-34n4iv", "sourceURL": "mapbox://meghabyte.2bxg6b9f" },
    { "sourceLayer": "idaho-8765po", "sourceURL": "mapbox://meghabyte.a180uah9" },
    { "sourceLayer": "guam-c3ymh3", "sourceURL": "mapbox://meghabyte.bb9djj05" },
    { "sourceLayer": "illinois-9y0l0h", "sourceURL": "mapbox://meghabyte.ac7v02uw" },
    { "sourceLayer": "dc-d63u8r", "sourceURL": "mapbox://meghabyte.3rgsvxkc" },
    { "sourceLayer": "delaware-bhosqd", "sourceURL": "mapbox://meghabyte.476hz1pz" },
    { "sourceLayer": "florida-0iw64a", "sourceURL": "mapbox://meghabyte.5rdwjrh9" },
    { "sourceLayer": "marina_islands-41ua7e", "sourceURL": "mapbox://meghabyte.5d675bvw" },
    { "sourceLayer": "indiana-b7l30f", "sourceURL": "mapbox://meghabyte.7q0vtsj5" },
    { "sourceLayer": "connecticut-0drdvg", "sourceURL": "mapbox://meghabyte.36786vn9" },
    { "sourceLayer": "colorado-37343z", "sourceURL": "mapbox://meghabyte.0ioxabdx" },
    { "sourceLayer": "georgia-4xoofg", "sourceURL": "mapbox://meghabyte.3stswfu8" },
    { "sourceLayer": "samoa-0upg6q", "sourceURL": "mapbox://meghabyte.dsgyamz0" },
    { "sourceLayer": "alaska-7sacrb", "sourceURL": "mapbox://meghabyte.26h4rvji" },
    { "sourceLayer": "arizona-0xkde3", "sourceURL": "mapbox://meghabyte.1ze2f7je" },
    { "sourceLayer": "arkansas-dcbg72", "sourceURL": "mapbox://meghabyte.3dd2vzmm" },
    { "sourceLayer": "alabama-7qk156", "sourceURL": "mapbox://meghabyte.axjhrole" },
    { "sourceLayer": "louisiana-bl5p3f", "sourceURL": "mapbox://meghabyte.di5hzmli" },
    { "sourceLayer": "puerto_rico-c4f903", "sourceURL": "mapbox://meghabyte.6ga7s4y8" },
    { "sourceLayer": "north_dakota-8ndoqs", "sourceURL": "mapbox://meghabyte.91tvka7l" },
    { "sourceLayer": "oklahoma-43tc4i", "sourceURL": "mapbox://meghabyte.80ydutmo" },
    { "sourceLayer": "oregon-b400hj", "sourceURL": "mapbox://meghabyte.74vanshz" },
    { "sourceLayer": "new_jersey-bfsqx6", "sourceURL": "mapbox://meghabyte.c6qg6wi7" },
    { "sourceLayer": "new_hampshire-dnh8wl", "sourceURL": "mapbox://meghabyte.abdwrkjp" },
    { "sourceLayer": "new_york-d90nlv", "sourceURL": "mapbox://meghabyte.63txha6r" },
    { "sourceLayer": "nevada-deuc62", "sourceURL": "mapbox://meghabyte.9s8ancwz" },
    { "sourceLayer": "nebraska-ctr88k", "sourceURL": "mapbox://meghabyte.auhhg1qr" },
    { "sourceLayer": "pennsylvania-32hw1n", "sourceURL": "mapbox://meghabyte.74giprnb" },
    { "sourceLayer": "new_mexico-3ikl2a", "sourceURL": "mapbox://meghabyte.38lde3fu" },
    { "sourceLayer": "ohio-6qh2hg", "sourceURL": "mapbox://meghabyte.cph75mnf" },
    { "sourceLayer": "montana-ajp2xu", "sourceURL": "mapbox://meghabyte.4ztugbfj" },
    { "sourceLayer": "north_carolina-7lsq0k", "sourceURL": "mapbox://meghabyte.414b3sc4" },
    { "sourceLayer": "michigan-0zitwe", "sourceURL": "mapbox://meghabyte.d71hz0zq" },
    { "sourceLayer": "missouri-al6asq", "sourceURL": "mapbox://meghabyte.bsh422ex" },
    { "sourceLayer": "massachusetts-1p0zje", "sourceURL": "mapbox://meghabyte.63q51vwl" },
    { "sourceLayer": "mississippi-3nl299", "sourceURL": "mapbox://meghabyte.18k9f9v1" },
    { "sourceLayer": "minnesota-1r6mxv", "sourceURL": "mapbox://meghabyte.7gxkg2l1" },
    { "sourceLayer": "maryland-8hvqn0", "sourceURL": "mapbox://meghabyte.8kyq1v9s" },
    { "sourceLayer": "maine-1pmoki", "sourceURL": "mapbox://meghabyte.82kwc72j" },
];

export default stateLayer;